server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: /api
spring:
  datasource:
    url: jdbc:mysql://${DATASOURCE_URL:127.0.0.1:3306/security}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowPublicKeyRetrieval=true&useSSL=false
    username: ${DATASOURCE_USERNAME:root}
    password: ${DATASOURCE_PASSWORD:123456}
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      pool-name: MyHikariCP
      max-lifetime: 1800000
      connection-timeout: 10000
      connection-test-query: SELECT 1
  servlet:
    multipart:
      max-file-size: 10MB #限制单个文件的最大值 1MB
      max-request-size: 100MB # 限制上传的多个文件的总大小
  redis:
    database: ${REDIS_DATABASE:0}
    host: ${REDIS_HOST:127.0.0.1}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:}
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0


mybatis-plus:
  # xml扫描，多个目录用逗号或者分号分隔（告诉 Mapper 所对应的 XML 文件位置）
  mapper-locations: classpath:/mapper/**/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
  global-config:
    db-config:
      id-type: auto

## swagger自定义配置属性
swagger:
  enabled: true
  title: dt-commercialization在线接口平台
  description: dt-commercialization服务相关接口



# jwt
jwt:
  header: Authorization
  secret: cuAihCz53DZRjZwbsGcZJ2Ai6At+T142uphtJMsk7iQ=
  expiration: 3600
  tokenHead: ""
  pub-uris:
    # 开放接口
    - "/login"
    - "/register"
    # swagger文档接口
    - "/**/swagger-resources"
    - "/**/api-docs"
    - "/**/doc.html"
    # 服务健康检查
    - "/sys/healthCheck"
  static-sources:
    #静态资源
    - "/*.html"
    - "/favicon.ico"
    - "/**/*.html"
    - "/**/*.css"
    - "/**/*.js"


#mysqltomd
mysqltomd:
  # 文件下载路径
  file-path:
  # 排除表名称
  exclude-table:
  # 排除字段名称
  exclude-field:
  # 输出表名称
  appoint-table:

