// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: IotWsMessage.proto

package com.example.springframe.entity.proto;

public final class IotWsMessage {
  private IotWsMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface IotWsMessageListOrBuilder extends
      // @@protoc_insertion_point(interface_extends:IotWsMessageList)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .WsMessage wsMessages = 1;</code>
     */
    java.util.List<com.example.springframe.entity.proto.IotWsMessage.WsMessage> 
        getWsMessagesList();
    /**
     * <code>repeated .WsMessage wsMessages = 1;</code>
     */
    com.example.springframe.entity.proto.IotWsMessage.WsMessage getWsMessages(int index);
    /**
     * <code>repeated .WsMessage wsMessages = 1;</code>
     */
    int getWsMessagesCount();
    /**
     * <code>repeated .WsMessage wsMessages = 1;</code>
     */
    java.util.List<? extends com.example.springframe.entity.proto.IotWsMessage.WsMessageOrBuilder> 
        getWsMessagesOrBuilderList();
    /**
     * <code>repeated .WsMessage wsMessages = 1;</code>
     */
    com.example.springframe.entity.proto.IotWsMessage.WsMessageOrBuilder getWsMessagesOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code IotWsMessageList}
   */
  public static final class IotWsMessageList extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:IotWsMessageList)
      IotWsMessageListOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use IotWsMessageList.newBuilder() to construct.
    private IotWsMessageList(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private IotWsMessageList() {
      wsMessages_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new IotWsMessageList();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.springframe.entity.proto.IotWsMessage.internal_static_IotWsMessageList_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.springframe.entity.proto.IotWsMessage.internal_static_IotWsMessageList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.springframe.entity.proto.IotWsMessage.IotWsMessageList.class, com.example.springframe.entity.proto.IotWsMessage.IotWsMessageList.Builder.class);
    }

    public static final int WSMESSAGES_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private java.util.List<com.example.springframe.entity.proto.IotWsMessage.WsMessage> wsMessages_;
    /**
     * <code>repeated .WsMessage wsMessages = 1;</code>
     */
    @java.lang.Override
    public java.util.List<com.example.springframe.entity.proto.IotWsMessage.WsMessage> getWsMessagesList() {
      return wsMessages_;
    }
    /**
     * <code>repeated .WsMessage wsMessages = 1;</code>
     */
    @java.lang.Override
    public java.util.List<? extends com.example.springframe.entity.proto.IotWsMessage.WsMessageOrBuilder> 
        getWsMessagesOrBuilderList() {
      return wsMessages_;
    }
    /**
     * <code>repeated .WsMessage wsMessages = 1;</code>
     */
    @java.lang.Override
    public int getWsMessagesCount() {
      return wsMessages_.size();
    }
    /**
     * <code>repeated .WsMessage wsMessages = 1;</code>
     */
    @java.lang.Override
    public com.example.springframe.entity.proto.IotWsMessage.WsMessage getWsMessages(int index) {
      return wsMessages_.get(index);
    }
    /**
     * <code>repeated .WsMessage wsMessages = 1;</code>
     */
    @java.lang.Override
    public com.example.springframe.entity.proto.IotWsMessage.WsMessageOrBuilder getWsMessagesOrBuilder(
        int index) {
      return wsMessages_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < wsMessages_.size(); i++) {
        output.writeMessage(1, wsMessages_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < wsMessages_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, wsMessages_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.example.springframe.entity.proto.IotWsMessage.IotWsMessageList)) {
        return super.equals(obj);
      }
      com.example.springframe.entity.proto.IotWsMessage.IotWsMessageList other = (com.example.springframe.entity.proto.IotWsMessage.IotWsMessageList) obj;

      if (!getWsMessagesList()
          .equals(other.getWsMessagesList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getWsMessagesCount() > 0) {
        hash = (37 * hash) + WSMESSAGES_FIELD_NUMBER;
        hash = (53 * hash) + getWsMessagesList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.example.springframe.entity.proto.IotWsMessage.IotWsMessageList parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.springframe.entity.proto.IotWsMessage.IotWsMessageList parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.springframe.entity.proto.IotWsMessage.IotWsMessageList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.springframe.entity.proto.IotWsMessage.IotWsMessageList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.springframe.entity.proto.IotWsMessage.IotWsMessageList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.springframe.entity.proto.IotWsMessage.IotWsMessageList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.springframe.entity.proto.IotWsMessage.IotWsMessageList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.example.springframe.entity.proto.IotWsMessage.IotWsMessageList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.example.springframe.entity.proto.IotWsMessage.IotWsMessageList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.example.springframe.entity.proto.IotWsMessage.IotWsMessageList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.example.springframe.entity.proto.IotWsMessage.IotWsMessageList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.example.springframe.entity.proto.IotWsMessage.IotWsMessageList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.example.springframe.entity.proto.IotWsMessage.IotWsMessageList prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code IotWsMessageList}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:IotWsMessageList)
        com.example.springframe.entity.proto.IotWsMessage.IotWsMessageListOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.example.springframe.entity.proto.IotWsMessage.internal_static_IotWsMessageList_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.example.springframe.entity.proto.IotWsMessage.internal_static_IotWsMessageList_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.example.springframe.entity.proto.IotWsMessage.IotWsMessageList.class, com.example.springframe.entity.proto.IotWsMessage.IotWsMessageList.Builder.class);
      }

      // Construct using com.example.springframe.entity.proto.IotWsMessage.IotWsMessageList.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        if (wsMessagesBuilder_ == null) {
          wsMessages_ = java.util.Collections.emptyList();
        } else {
          wsMessages_ = null;
          wsMessagesBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.example.springframe.entity.proto.IotWsMessage.internal_static_IotWsMessageList_descriptor;
      }

      @java.lang.Override
      public com.example.springframe.entity.proto.IotWsMessage.IotWsMessageList getDefaultInstanceForType() {
        return com.example.springframe.entity.proto.IotWsMessage.IotWsMessageList.getDefaultInstance();
      }

      @java.lang.Override
      public com.example.springframe.entity.proto.IotWsMessage.IotWsMessageList build() {
        com.example.springframe.entity.proto.IotWsMessage.IotWsMessageList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.example.springframe.entity.proto.IotWsMessage.IotWsMessageList buildPartial() {
        com.example.springframe.entity.proto.IotWsMessage.IotWsMessageList result = new com.example.springframe.entity.proto.IotWsMessage.IotWsMessageList(this);
        buildPartialRepeatedFields(result);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartialRepeatedFields(com.example.springframe.entity.proto.IotWsMessage.IotWsMessageList result) {
        if (wsMessagesBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            wsMessages_ = java.util.Collections.unmodifiableList(wsMessages_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.wsMessages_ = wsMessages_;
        } else {
          result.wsMessages_ = wsMessagesBuilder_.build();
        }
      }

      private void buildPartial0(com.example.springframe.entity.proto.IotWsMessage.IotWsMessageList result) {
        int from_bitField0_ = bitField0_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.example.springframe.entity.proto.IotWsMessage.IotWsMessageList) {
          return mergeFrom((com.example.springframe.entity.proto.IotWsMessage.IotWsMessageList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.example.springframe.entity.proto.IotWsMessage.IotWsMessageList other) {
        if (other == com.example.springframe.entity.proto.IotWsMessage.IotWsMessageList.getDefaultInstance()) return this;
        if (wsMessagesBuilder_ == null) {
          if (!other.wsMessages_.isEmpty()) {
            if (wsMessages_.isEmpty()) {
              wsMessages_ = other.wsMessages_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureWsMessagesIsMutable();
              wsMessages_.addAll(other.wsMessages_);
            }
            onChanged();
          }
        } else {
          if (!other.wsMessages_.isEmpty()) {
            if (wsMessagesBuilder_.isEmpty()) {
              wsMessagesBuilder_.dispose();
              wsMessagesBuilder_ = null;
              wsMessages_ = other.wsMessages_;
              bitField0_ = (bitField0_ & ~0x00000001);
              wsMessagesBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getWsMessagesFieldBuilder() : null;
            } else {
              wsMessagesBuilder_.addAllMessages(other.wsMessages_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                com.example.springframe.entity.proto.IotWsMessage.WsMessage m =
                    input.readMessage(
                        com.example.springframe.entity.proto.IotWsMessage.WsMessage.parser(),
                        extensionRegistry);
                if (wsMessagesBuilder_ == null) {
                  ensureWsMessagesIsMutable();
                  wsMessages_.add(m);
                } else {
                  wsMessagesBuilder_.addMessage(m);
                }
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.util.List<com.example.springframe.entity.proto.IotWsMessage.WsMessage> wsMessages_ =
        java.util.Collections.emptyList();
      private void ensureWsMessagesIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          wsMessages_ = new java.util.ArrayList<com.example.springframe.entity.proto.IotWsMessage.WsMessage>(wsMessages_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.example.springframe.entity.proto.IotWsMessage.WsMessage, com.example.springframe.entity.proto.IotWsMessage.WsMessage.Builder, com.example.springframe.entity.proto.IotWsMessage.WsMessageOrBuilder> wsMessagesBuilder_;

      /**
       * <code>repeated .WsMessage wsMessages = 1;</code>
       */
      public java.util.List<com.example.springframe.entity.proto.IotWsMessage.WsMessage> getWsMessagesList() {
        if (wsMessagesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(wsMessages_);
        } else {
          return wsMessagesBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .WsMessage wsMessages = 1;</code>
       */
      public int getWsMessagesCount() {
        if (wsMessagesBuilder_ == null) {
          return wsMessages_.size();
        } else {
          return wsMessagesBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .WsMessage wsMessages = 1;</code>
       */
      public com.example.springframe.entity.proto.IotWsMessage.WsMessage getWsMessages(int index) {
        if (wsMessagesBuilder_ == null) {
          return wsMessages_.get(index);
        } else {
          return wsMessagesBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .WsMessage wsMessages = 1;</code>
       */
      public Builder setWsMessages(
          int index, com.example.springframe.entity.proto.IotWsMessage.WsMessage value) {
        if (wsMessagesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureWsMessagesIsMutable();
          wsMessages_.set(index, value);
          onChanged();
        } else {
          wsMessagesBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .WsMessage wsMessages = 1;</code>
       */
      public Builder setWsMessages(
          int index, com.example.springframe.entity.proto.IotWsMessage.WsMessage.Builder builderForValue) {
        if (wsMessagesBuilder_ == null) {
          ensureWsMessagesIsMutable();
          wsMessages_.set(index, builderForValue.build());
          onChanged();
        } else {
          wsMessagesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .WsMessage wsMessages = 1;</code>
       */
      public Builder addWsMessages(com.example.springframe.entity.proto.IotWsMessage.WsMessage value) {
        if (wsMessagesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureWsMessagesIsMutable();
          wsMessages_.add(value);
          onChanged();
        } else {
          wsMessagesBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .WsMessage wsMessages = 1;</code>
       */
      public Builder addWsMessages(
          int index, com.example.springframe.entity.proto.IotWsMessage.WsMessage value) {
        if (wsMessagesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureWsMessagesIsMutable();
          wsMessages_.add(index, value);
          onChanged();
        } else {
          wsMessagesBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .WsMessage wsMessages = 1;</code>
       */
      public Builder addWsMessages(
          com.example.springframe.entity.proto.IotWsMessage.WsMessage.Builder builderForValue) {
        if (wsMessagesBuilder_ == null) {
          ensureWsMessagesIsMutable();
          wsMessages_.add(builderForValue.build());
          onChanged();
        } else {
          wsMessagesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .WsMessage wsMessages = 1;</code>
       */
      public Builder addWsMessages(
          int index, com.example.springframe.entity.proto.IotWsMessage.WsMessage.Builder builderForValue) {
        if (wsMessagesBuilder_ == null) {
          ensureWsMessagesIsMutable();
          wsMessages_.add(index, builderForValue.build());
          onChanged();
        } else {
          wsMessagesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .WsMessage wsMessages = 1;</code>
       */
      public Builder addAllWsMessages(
          java.lang.Iterable<? extends com.example.springframe.entity.proto.IotWsMessage.WsMessage> values) {
        if (wsMessagesBuilder_ == null) {
          ensureWsMessagesIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, wsMessages_);
          onChanged();
        } else {
          wsMessagesBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .WsMessage wsMessages = 1;</code>
       */
      public Builder clearWsMessages() {
        if (wsMessagesBuilder_ == null) {
          wsMessages_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          wsMessagesBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .WsMessage wsMessages = 1;</code>
       */
      public Builder removeWsMessages(int index) {
        if (wsMessagesBuilder_ == null) {
          ensureWsMessagesIsMutable();
          wsMessages_.remove(index);
          onChanged();
        } else {
          wsMessagesBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .WsMessage wsMessages = 1;</code>
       */
      public com.example.springframe.entity.proto.IotWsMessage.WsMessage.Builder getWsMessagesBuilder(
          int index) {
        return getWsMessagesFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .WsMessage wsMessages = 1;</code>
       */
      public com.example.springframe.entity.proto.IotWsMessage.WsMessageOrBuilder getWsMessagesOrBuilder(
          int index) {
        if (wsMessagesBuilder_ == null) {
          return wsMessages_.get(index);  } else {
          return wsMessagesBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .WsMessage wsMessages = 1;</code>
       */
      public java.util.List<? extends com.example.springframe.entity.proto.IotWsMessage.WsMessageOrBuilder> 
           getWsMessagesOrBuilderList() {
        if (wsMessagesBuilder_ != null) {
          return wsMessagesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(wsMessages_);
        }
      }
      /**
       * <code>repeated .WsMessage wsMessages = 1;</code>
       */
      public com.example.springframe.entity.proto.IotWsMessage.WsMessage.Builder addWsMessagesBuilder() {
        return getWsMessagesFieldBuilder().addBuilder(
            com.example.springframe.entity.proto.IotWsMessage.WsMessage.getDefaultInstance());
      }
      /**
       * <code>repeated .WsMessage wsMessages = 1;</code>
       */
      public com.example.springframe.entity.proto.IotWsMessage.WsMessage.Builder addWsMessagesBuilder(
          int index) {
        return getWsMessagesFieldBuilder().addBuilder(
            index, com.example.springframe.entity.proto.IotWsMessage.WsMessage.getDefaultInstance());
      }
      /**
       * <code>repeated .WsMessage wsMessages = 1;</code>
       */
      public java.util.List<com.example.springframe.entity.proto.IotWsMessage.WsMessage.Builder> 
           getWsMessagesBuilderList() {
        return getWsMessagesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.example.springframe.entity.proto.IotWsMessage.WsMessage, com.example.springframe.entity.proto.IotWsMessage.WsMessage.Builder, com.example.springframe.entity.proto.IotWsMessage.WsMessageOrBuilder> 
          getWsMessagesFieldBuilder() {
        if (wsMessagesBuilder_ == null) {
          wsMessagesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.example.springframe.entity.proto.IotWsMessage.WsMessage, com.example.springframe.entity.proto.IotWsMessage.WsMessage.Builder, com.example.springframe.entity.proto.IotWsMessage.WsMessageOrBuilder>(
                  wsMessages_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          wsMessages_ = null;
        }
        return wsMessagesBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:IotWsMessageList)
    }

    // @@protoc_insertion_point(class_scope:IotWsMessageList)
    private static final com.example.springframe.entity.proto.IotWsMessage.IotWsMessageList DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.example.springframe.entity.proto.IotWsMessage.IotWsMessageList();
    }

    public static com.example.springframe.entity.proto.IotWsMessage.IotWsMessageList getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<IotWsMessageList>
        PARSER = new com.google.protobuf.AbstractParser<IotWsMessageList>() {
      @java.lang.Override
      public IotWsMessageList parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<IotWsMessageList> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<IotWsMessageList> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.example.springframe.entity.proto.IotWsMessage.IotWsMessageList getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface WsMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:WsMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string subscriptionId = 1;</code>
     * @return The subscriptionId.
     */
    java.lang.String getSubscriptionId();
    /**
     * <code>string subscriptionId = 1;</code>
     * @return The bytes for subscriptionId.
     */
    com.google.protobuf.ByteString
        getSubscriptionIdBytes();

    /**
     * <code>repeated .MessageData messageData = 2;</code>
     */
    java.util.List<com.example.springframe.entity.proto.IotWsMessage.MessageData> 
        getMessageDataList();
    /**
     * <code>repeated .MessageData messageData = 2;</code>
     */
    com.example.springframe.entity.proto.IotWsMessage.MessageData getMessageData(int index);
    /**
     * <code>repeated .MessageData messageData = 2;</code>
     */
    int getMessageDataCount();
    /**
     * <code>repeated .MessageData messageData = 2;</code>
     */
    java.util.List<? extends com.example.springframe.entity.proto.IotWsMessage.MessageDataOrBuilder> 
        getMessageDataOrBuilderList();
    /**
     * <code>repeated .MessageData messageData = 2;</code>
     */
    com.example.springframe.entity.proto.IotWsMessage.MessageDataOrBuilder getMessageDataOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code WsMessage}
   */
  public static final class WsMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:WsMessage)
      WsMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use WsMessage.newBuilder() to construct.
    private WsMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private WsMessage() {
      subscriptionId_ = "";
      messageData_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new WsMessage();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.springframe.entity.proto.IotWsMessage.internal_static_WsMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.springframe.entity.proto.IotWsMessage.internal_static_WsMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.springframe.entity.proto.IotWsMessage.WsMessage.class, com.example.springframe.entity.proto.IotWsMessage.WsMessage.Builder.class);
    }

    public static final int SUBSCRIPTIONID_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object subscriptionId_ = "";
    /**
     * <code>string subscriptionId = 1;</code>
     * @return The subscriptionId.
     */
    @java.lang.Override
    public java.lang.String getSubscriptionId() {
      java.lang.Object ref = subscriptionId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        subscriptionId_ = s;
        return s;
      }
    }
    /**
     * <code>string subscriptionId = 1;</code>
     * @return The bytes for subscriptionId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getSubscriptionIdBytes() {
      java.lang.Object ref = subscriptionId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        subscriptionId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MESSAGEDATA_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private java.util.List<com.example.springframe.entity.proto.IotWsMessage.MessageData> messageData_;
    /**
     * <code>repeated .MessageData messageData = 2;</code>
     */
    @java.lang.Override
    public java.util.List<com.example.springframe.entity.proto.IotWsMessage.MessageData> getMessageDataList() {
      return messageData_;
    }
    /**
     * <code>repeated .MessageData messageData = 2;</code>
     */
    @java.lang.Override
    public java.util.List<? extends com.example.springframe.entity.proto.IotWsMessage.MessageDataOrBuilder> 
        getMessageDataOrBuilderList() {
      return messageData_;
    }
    /**
     * <code>repeated .MessageData messageData = 2;</code>
     */
    @java.lang.Override
    public int getMessageDataCount() {
      return messageData_.size();
    }
    /**
     * <code>repeated .MessageData messageData = 2;</code>
     */
    @java.lang.Override
    public com.example.springframe.entity.proto.IotWsMessage.MessageData getMessageData(int index) {
      return messageData_.get(index);
    }
    /**
     * <code>repeated .MessageData messageData = 2;</code>
     */
    @java.lang.Override
    public com.example.springframe.entity.proto.IotWsMessage.MessageDataOrBuilder getMessageDataOrBuilder(
        int index) {
      return messageData_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(subscriptionId_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, subscriptionId_);
      }
      for (int i = 0; i < messageData_.size(); i++) {
        output.writeMessage(2, messageData_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(subscriptionId_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, subscriptionId_);
      }
      for (int i = 0; i < messageData_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, messageData_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.example.springframe.entity.proto.IotWsMessage.WsMessage)) {
        return super.equals(obj);
      }
      com.example.springframe.entity.proto.IotWsMessage.WsMessage other = (com.example.springframe.entity.proto.IotWsMessage.WsMessage) obj;

      if (!getSubscriptionId()
          .equals(other.getSubscriptionId())) return false;
      if (!getMessageDataList()
          .equals(other.getMessageDataList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SUBSCRIPTIONID_FIELD_NUMBER;
      hash = (53 * hash) + getSubscriptionId().hashCode();
      if (getMessageDataCount() > 0) {
        hash = (37 * hash) + MESSAGEDATA_FIELD_NUMBER;
        hash = (53 * hash) + getMessageDataList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.example.springframe.entity.proto.IotWsMessage.WsMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.springframe.entity.proto.IotWsMessage.WsMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.springframe.entity.proto.IotWsMessage.WsMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.springframe.entity.proto.IotWsMessage.WsMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.springframe.entity.proto.IotWsMessage.WsMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.springframe.entity.proto.IotWsMessage.WsMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.springframe.entity.proto.IotWsMessage.WsMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.example.springframe.entity.proto.IotWsMessage.WsMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.example.springframe.entity.proto.IotWsMessage.WsMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.example.springframe.entity.proto.IotWsMessage.WsMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.example.springframe.entity.proto.IotWsMessage.WsMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.example.springframe.entity.proto.IotWsMessage.WsMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.example.springframe.entity.proto.IotWsMessage.WsMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code WsMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:WsMessage)
        com.example.springframe.entity.proto.IotWsMessage.WsMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.example.springframe.entity.proto.IotWsMessage.internal_static_WsMessage_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.example.springframe.entity.proto.IotWsMessage.internal_static_WsMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.example.springframe.entity.proto.IotWsMessage.WsMessage.class, com.example.springframe.entity.proto.IotWsMessage.WsMessage.Builder.class);
      }

      // Construct using com.example.springframe.entity.proto.IotWsMessage.WsMessage.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        subscriptionId_ = "";
        if (messageDataBuilder_ == null) {
          messageData_ = java.util.Collections.emptyList();
        } else {
          messageData_ = null;
          messageDataBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.example.springframe.entity.proto.IotWsMessage.internal_static_WsMessage_descriptor;
      }

      @java.lang.Override
      public com.example.springframe.entity.proto.IotWsMessage.WsMessage getDefaultInstanceForType() {
        return com.example.springframe.entity.proto.IotWsMessage.WsMessage.getDefaultInstance();
      }

      @java.lang.Override
      public com.example.springframe.entity.proto.IotWsMessage.WsMessage build() {
        com.example.springframe.entity.proto.IotWsMessage.WsMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.example.springframe.entity.proto.IotWsMessage.WsMessage buildPartial() {
        com.example.springframe.entity.proto.IotWsMessage.WsMessage result = new com.example.springframe.entity.proto.IotWsMessage.WsMessage(this);
        buildPartialRepeatedFields(result);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartialRepeatedFields(com.example.springframe.entity.proto.IotWsMessage.WsMessage result) {
        if (messageDataBuilder_ == null) {
          if (((bitField0_ & 0x00000002) != 0)) {
            messageData_ = java.util.Collections.unmodifiableList(messageData_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.messageData_ = messageData_;
        } else {
          result.messageData_ = messageDataBuilder_.build();
        }
      }

      private void buildPartial0(com.example.springframe.entity.proto.IotWsMessage.WsMessage result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.subscriptionId_ = subscriptionId_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.example.springframe.entity.proto.IotWsMessage.WsMessage) {
          return mergeFrom((com.example.springframe.entity.proto.IotWsMessage.WsMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.example.springframe.entity.proto.IotWsMessage.WsMessage other) {
        if (other == com.example.springframe.entity.proto.IotWsMessage.WsMessage.getDefaultInstance()) return this;
        if (!other.getSubscriptionId().isEmpty()) {
          subscriptionId_ = other.subscriptionId_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (messageDataBuilder_ == null) {
          if (!other.messageData_.isEmpty()) {
            if (messageData_.isEmpty()) {
              messageData_ = other.messageData_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureMessageDataIsMutable();
              messageData_.addAll(other.messageData_);
            }
            onChanged();
          }
        } else {
          if (!other.messageData_.isEmpty()) {
            if (messageDataBuilder_.isEmpty()) {
              messageDataBuilder_.dispose();
              messageDataBuilder_ = null;
              messageData_ = other.messageData_;
              bitField0_ = (bitField0_ & ~0x00000002);
              messageDataBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getMessageDataFieldBuilder() : null;
            } else {
              messageDataBuilder_.addAllMessages(other.messageData_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                subscriptionId_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                com.example.springframe.entity.proto.IotWsMessage.MessageData m =
                    input.readMessage(
                        com.example.springframe.entity.proto.IotWsMessage.MessageData.parser(),
                        extensionRegistry);
                if (messageDataBuilder_ == null) {
                  ensureMessageDataIsMutable();
                  messageData_.add(m);
                } else {
                  messageDataBuilder_.addMessage(m);
                }
                break;
              } // case 18
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object subscriptionId_ = "";
      /**
       * <code>string subscriptionId = 1;</code>
       * @return The subscriptionId.
       */
      public java.lang.String getSubscriptionId() {
        java.lang.Object ref = subscriptionId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          subscriptionId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string subscriptionId = 1;</code>
       * @return The bytes for subscriptionId.
       */
      public com.google.protobuf.ByteString
          getSubscriptionIdBytes() {
        java.lang.Object ref = subscriptionId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          subscriptionId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string subscriptionId = 1;</code>
       * @param value The subscriptionId to set.
       * @return This builder for chaining.
       */
      public Builder setSubscriptionId(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        subscriptionId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string subscriptionId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearSubscriptionId() {
        subscriptionId_ = getDefaultInstance().getSubscriptionId();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string subscriptionId = 1;</code>
       * @param value The bytes for subscriptionId to set.
       * @return This builder for chaining.
       */
      public Builder setSubscriptionIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        subscriptionId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private java.util.List<com.example.springframe.entity.proto.IotWsMessage.MessageData> messageData_ =
        java.util.Collections.emptyList();
      private void ensureMessageDataIsMutable() {
        if (!((bitField0_ & 0x00000002) != 0)) {
          messageData_ = new java.util.ArrayList<com.example.springframe.entity.proto.IotWsMessage.MessageData>(messageData_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.example.springframe.entity.proto.IotWsMessage.MessageData, com.example.springframe.entity.proto.IotWsMessage.MessageData.Builder, com.example.springframe.entity.proto.IotWsMessage.MessageDataOrBuilder> messageDataBuilder_;

      /**
       * <code>repeated .MessageData messageData = 2;</code>
       */
      public java.util.List<com.example.springframe.entity.proto.IotWsMessage.MessageData> getMessageDataList() {
        if (messageDataBuilder_ == null) {
          return java.util.Collections.unmodifiableList(messageData_);
        } else {
          return messageDataBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .MessageData messageData = 2;</code>
       */
      public int getMessageDataCount() {
        if (messageDataBuilder_ == null) {
          return messageData_.size();
        } else {
          return messageDataBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .MessageData messageData = 2;</code>
       */
      public com.example.springframe.entity.proto.IotWsMessage.MessageData getMessageData(int index) {
        if (messageDataBuilder_ == null) {
          return messageData_.get(index);
        } else {
          return messageDataBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .MessageData messageData = 2;</code>
       */
      public Builder setMessageData(
          int index, com.example.springframe.entity.proto.IotWsMessage.MessageData value) {
        if (messageDataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMessageDataIsMutable();
          messageData_.set(index, value);
          onChanged();
        } else {
          messageDataBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .MessageData messageData = 2;</code>
       */
      public Builder setMessageData(
          int index, com.example.springframe.entity.proto.IotWsMessage.MessageData.Builder builderForValue) {
        if (messageDataBuilder_ == null) {
          ensureMessageDataIsMutable();
          messageData_.set(index, builderForValue.build());
          onChanged();
        } else {
          messageDataBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .MessageData messageData = 2;</code>
       */
      public Builder addMessageData(com.example.springframe.entity.proto.IotWsMessage.MessageData value) {
        if (messageDataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMessageDataIsMutable();
          messageData_.add(value);
          onChanged();
        } else {
          messageDataBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .MessageData messageData = 2;</code>
       */
      public Builder addMessageData(
          int index, com.example.springframe.entity.proto.IotWsMessage.MessageData value) {
        if (messageDataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMessageDataIsMutable();
          messageData_.add(index, value);
          onChanged();
        } else {
          messageDataBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .MessageData messageData = 2;</code>
       */
      public Builder addMessageData(
          com.example.springframe.entity.proto.IotWsMessage.MessageData.Builder builderForValue) {
        if (messageDataBuilder_ == null) {
          ensureMessageDataIsMutable();
          messageData_.add(builderForValue.build());
          onChanged();
        } else {
          messageDataBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .MessageData messageData = 2;</code>
       */
      public Builder addMessageData(
          int index, com.example.springframe.entity.proto.IotWsMessage.MessageData.Builder builderForValue) {
        if (messageDataBuilder_ == null) {
          ensureMessageDataIsMutable();
          messageData_.add(index, builderForValue.build());
          onChanged();
        } else {
          messageDataBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .MessageData messageData = 2;</code>
       */
      public Builder addAllMessageData(
          java.lang.Iterable<? extends com.example.springframe.entity.proto.IotWsMessage.MessageData> values) {
        if (messageDataBuilder_ == null) {
          ensureMessageDataIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, messageData_);
          onChanged();
        } else {
          messageDataBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .MessageData messageData = 2;</code>
       */
      public Builder clearMessageData() {
        if (messageDataBuilder_ == null) {
          messageData_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          messageDataBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .MessageData messageData = 2;</code>
       */
      public Builder removeMessageData(int index) {
        if (messageDataBuilder_ == null) {
          ensureMessageDataIsMutable();
          messageData_.remove(index);
          onChanged();
        } else {
          messageDataBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .MessageData messageData = 2;</code>
       */
      public com.example.springframe.entity.proto.IotWsMessage.MessageData.Builder getMessageDataBuilder(
          int index) {
        return getMessageDataFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .MessageData messageData = 2;</code>
       */
      public com.example.springframe.entity.proto.IotWsMessage.MessageDataOrBuilder getMessageDataOrBuilder(
          int index) {
        if (messageDataBuilder_ == null) {
          return messageData_.get(index);  } else {
          return messageDataBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .MessageData messageData = 2;</code>
       */
      public java.util.List<? extends com.example.springframe.entity.proto.IotWsMessage.MessageDataOrBuilder> 
           getMessageDataOrBuilderList() {
        if (messageDataBuilder_ != null) {
          return messageDataBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(messageData_);
        }
      }
      /**
       * <code>repeated .MessageData messageData = 2;</code>
       */
      public com.example.springframe.entity.proto.IotWsMessage.MessageData.Builder addMessageDataBuilder() {
        return getMessageDataFieldBuilder().addBuilder(
            com.example.springframe.entity.proto.IotWsMessage.MessageData.getDefaultInstance());
      }
      /**
       * <code>repeated .MessageData messageData = 2;</code>
       */
      public com.example.springframe.entity.proto.IotWsMessage.MessageData.Builder addMessageDataBuilder(
          int index) {
        return getMessageDataFieldBuilder().addBuilder(
            index, com.example.springframe.entity.proto.IotWsMessage.MessageData.getDefaultInstance());
      }
      /**
       * <code>repeated .MessageData messageData = 2;</code>
       */
      public java.util.List<com.example.springframe.entity.proto.IotWsMessage.MessageData.Builder> 
           getMessageDataBuilderList() {
        return getMessageDataFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.example.springframe.entity.proto.IotWsMessage.MessageData, com.example.springframe.entity.proto.IotWsMessage.MessageData.Builder, com.example.springframe.entity.proto.IotWsMessage.MessageDataOrBuilder> 
          getMessageDataFieldBuilder() {
        if (messageDataBuilder_ == null) {
          messageDataBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.example.springframe.entity.proto.IotWsMessage.MessageData, com.example.springframe.entity.proto.IotWsMessage.MessageData.Builder, com.example.springframe.entity.proto.IotWsMessage.MessageDataOrBuilder>(
                  messageData_,
                  ((bitField0_ & 0x00000002) != 0),
                  getParentForChildren(),
                  isClean());
          messageData_ = null;
        }
        return messageDataBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:WsMessage)
    }

    // @@protoc_insertion_point(class_scope:WsMessage)
    private static final com.example.springframe.entity.proto.IotWsMessage.WsMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.example.springframe.entity.proto.IotWsMessage.WsMessage();
    }

    public static com.example.springframe.entity.proto.IotWsMessage.WsMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<WsMessage>
        PARSER = new com.google.protobuf.AbstractParser<WsMessage>() {
      @java.lang.Override
      public WsMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<WsMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<WsMessage> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.example.springframe.entity.proto.IotWsMessage.WsMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface MessageDataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:MessageData)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string point = 1;</code>
     * @return The point.
     */
    java.lang.String getPoint();
    /**
     * <code>string point = 1;</code>
     * @return The bytes for point.
     */
    com.google.protobuf.ByteString
        getPointBytes();

    /**
     * <code>string value = 2;</code>
     * @return The value.
     */
    java.lang.String getValue();
    /**
     * <code>string value = 2;</code>
     * @return The bytes for value.
     */
    com.google.protobuf.ByteString
        getValueBytes();
  }
  /**
   * Protobuf type {@code MessageData}
   */
  public static final class MessageData extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:MessageData)
      MessageDataOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MessageData.newBuilder() to construct.
    private MessageData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MessageData() {
      point_ = "";
      value_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new MessageData();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.springframe.entity.proto.IotWsMessage.internal_static_MessageData_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.springframe.entity.proto.IotWsMessage.internal_static_MessageData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.springframe.entity.proto.IotWsMessage.MessageData.class, com.example.springframe.entity.proto.IotWsMessage.MessageData.Builder.class);
    }

    public static final int POINT_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object point_ = "";
    /**
     * <code>string point = 1;</code>
     * @return The point.
     */
    @java.lang.Override
    public java.lang.String getPoint() {
      java.lang.Object ref = point_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        point_ = s;
        return s;
      }
    }
    /**
     * <code>string point = 1;</code>
     * @return The bytes for point.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getPointBytes() {
      java.lang.Object ref = point_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        point_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int VALUE_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object value_ = "";
    /**
     * <code>string value = 2;</code>
     * @return The value.
     */
    @java.lang.Override
    public java.lang.String getValue() {
      java.lang.Object ref = value_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        value_ = s;
        return s;
      }
    }
    /**
     * <code>string value = 2;</code>
     * @return The bytes for value.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getValueBytes() {
      java.lang.Object ref = value_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        value_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(point_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, point_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(value_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, value_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(point_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, point_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(value_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, value_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.example.springframe.entity.proto.IotWsMessage.MessageData)) {
        return super.equals(obj);
      }
      com.example.springframe.entity.proto.IotWsMessage.MessageData other = (com.example.springframe.entity.proto.IotWsMessage.MessageData) obj;

      if (!getPoint()
          .equals(other.getPoint())) return false;
      if (!getValue()
          .equals(other.getValue())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + POINT_FIELD_NUMBER;
      hash = (53 * hash) + getPoint().hashCode();
      hash = (37 * hash) + VALUE_FIELD_NUMBER;
      hash = (53 * hash) + getValue().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.example.springframe.entity.proto.IotWsMessage.MessageData parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.springframe.entity.proto.IotWsMessage.MessageData parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.springframe.entity.proto.IotWsMessage.MessageData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.springframe.entity.proto.IotWsMessage.MessageData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.springframe.entity.proto.IotWsMessage.MessageData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.springframe.entity.proto.IotWsMessage.MessageData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.springframe.entity.proto.IotWsMessage.MessageData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.example.springframe.entity.proto.IotWsMessage.MessageData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.example.springframe.entity.proto.IotWsMessage.MessageData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.example.springframe.entity.proto.IotWsMessage.MessageData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.example.springframe.entity.proto.IotWsMessage.MessageData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.example.springframe.entity.proto.IotWsMessage.MessageData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.example.springframe.entity.proto.IotWsMessage.MessageData prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code MessageData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:MessageData)
        com.example.springframe.entity.proto.IotWsMessage.MessageDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.example.springframe.entity.proto.IotWsMessage.internal_static_MessageData_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.example.springframe.entity.proto.IotWsMessage.internal_static_MessageData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.example.springframe.entity.proto.IotWsMessage.MessageData.class, com.example.springframe.entity.proto.IotWsMessage.MessageData.Builder.class);
      }

      // Construct using com.example.springframe.entity.proto.IotWsMessage.MessageData.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        point_ = "";
        value_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.example.springframe.entity.proto.IotWsMessage.internal_static_MessageData_descriptor;
      }

      @java.lang.Override
      public com.example.springframe.entity.proto.IotWsMessage.MessageData getDefaultInstanceForType() {
        return com.example.springframe.entity.proto.IotWsMessage.MessageData.getDefaultInstance();
      }

      @java.lang.Override
      public com.example.springframe.entity.proto.IotWsMessage.MessageData build() {
        com.example.springframe.entity.proto.IotWsMessage.MessageData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.example.springframe.entity.proto.IotWsMessage.MessageData buildPartial() {
        com.example.springframe.entity.proto.IotWsMessage.MessageData result = new com.example.springframe.entity.proto.IotWsMessage.MessageData(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.example.springframe.entity.proto.IotWsMessage.MessageData result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.point_ = point_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.value_ = value_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.example.springframe.entity.proto.IotWsMessage.MessageData) {
          return mergeFrom((com.example.springframe.entity.proto.IotWsMessage.MessageData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.example.springframe.entity.proto.IotWsMessage.MessageData other) {
        if (other == com.example.springframe.entity.proto.IotWsMessage.MessageData.getDefaultInstance()) return this;
        if (!other.getPoint().isEmpty()) {
          point_ = other.point_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (!other.getValue().isEmpty()) {
          value_ = other.value_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                point_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                value_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object point_ = "";
      /**
       * <code>string point = 1;</code>
       * @return The point.
       */
      public java.lang.String getPoint() {
        java.lang.Object ref = point_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          point_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string point = 1;</code>
       * @return The bytes for point.
       */
      public com.google.protobuf.ByteString
          getPointBytes() {
        java.lang.Object ref = point_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          point_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string point = 1;</code>
       * @param value The point to set.
       * @return This builder for chaining.
       */
      public Builder setPoint(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        point_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string point = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearPoint() {
        point_ = getDefaultInstance().getPoint();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string point = 1;</code>
       * @param value The bytes for point to set.
       * @return This builder for chaining.
       */
      public Builder setPointBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        point_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private java.lang.Object value_ = "";
      /**
       * <code>string value = 2;</code>
       * @return The value.
       */
      public java.lang.String getValue() {
        java.lang.Object ref = value_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          value_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string value = 2;</code>
       * @return The bytes for value.
       */
      public com.google.protobuf.ByteString
          getValueBytes() {
        java.lang.Object ref = value_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          value_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string value = 2;</code>
       * @param value The value to set.
       * @return This builder for chaining.
       */
      public Builder setValue(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        value_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>string value = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearValue() {
        value_ = getDefaultInstance().getValue();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>string value = 2;</code>
       * @param value The bytes for value to set.
       * @return This builder for chaining.
       */
      public Builder setValueBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        value_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:MessageData)
    }

    // @@protoc_insertion_point(class_scope:MessageData)
    private static final com.example.springframe.entity.proto.IotWsMessage.MessageData DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.example.springframe.entity.proto.IotWsMessage.MessageData();
    }

    public static com.example.springframe.entity.proto.IotWsMessage.MessageData getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MessageData>
        PARSER = new com.google.protobuf.AbstractParser<MessageData>() {
      @java.lang.Override
      public MessageData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<MessageData> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MessageData> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.example.springframe.entity.proto.IotWsMessage.MessageData getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_IotWsMessageList_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_IotWsMessageList_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_WsMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_WsMessage_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MessageData_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MessageData_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022IotWsMessage.proto\"2\n\020IotWsMessageList" +
      "\022\036\n\nwsMessages\030\001 \003(\0132\n.WsMessage\"F\n\tWsMe" +
      "ssage\022\026\n\016subscriptionId\030\001 \001(\t\022!\n\013message" +
      "Data\030\002 \003(\0132\014.MessageData\"+\n\013MessageData\022" +
      "\r\n\005point\030\001 \001(\t\022\r\n\005value\030\002 \001(\tB(\n$com.exa" +
      "mple.springframe.entity.protoP\000b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_IotWsMessageList_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_IotWsMessageList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_IotWsMessageList_descriptor,
        new java.lang.String[] { "WsMessages", });
    internal_static_WsMessage_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_WsMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_WsMessage_descriptor,
        new java.lang.String[] { "SubscriptionId", "MessageData", });
    internal_static_MessageData_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_MessageData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MessageData_descriptor,
        new java.lang.String[] { "Point", "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
